sudo: required

services:
  - docker

language: node_js

node_js:
  - "9"

cache:
  directories:
    - node_modules
    - client/node_modules
    - server/node_modules

install:
  - npm i
  - cd $TRAVIS_BUILD_DIR/

before_script:
  - npm run dependencyCheck

script:
  - npm test
  - npm run build

after_success:
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
   docker login --username="$DOCKER_USERNAME" --email="$DOCKER_EMAIL" --password="$DOCKER_PASSWORD";
   docker push xeronimus/poinz;
   fi
