language: node_js
node_js:
  - "4.1"
  - "4.2"
cache:
  directories:
    - node_modules
    - client/node_modules
    - server/node_modules
install:
  - npm i
  - cd $TRAVIS_BUILD_DIR/client && npm i
  - cd $TRAVIS_BUILD_DIR/server && npm i
  - cd $TRAVIS_BUILD_DIR/

