os: linux

services:
  - docker

language: node_js

node_js:
  - "16"

cache:
  directories:
    - node_modules
    - client/node_modules
    - server/node_modules

install:
  - npm i
  - cd $TRAVIS_BUILD_DIR/

before_script:
  - npm run dependencyCheck

script:
  - npm test
  - npm run build
